### ISSUE TITLE
make bossbar working with hours

### ISSUE THREAD

**Issue by XneddyX** [FlexXx1212/MinecraftTimerDatapack#1]
add in load:
`scoreboard players set 3600 time 3600`

change: 
`execute if score running time matches 1 if score first time <= running time run scoreboard players operation first time += min time
execute if score running time matches 1 if score first time = hour time run scoreboard players operation first time *= 60 time
`
to
`execute if score running time matches 1 if score first time <= running time run scoreboard players operation first time += hour time
execute if score running time matches 1 if score first time = hour time run scoreboard players operation first time *= 3600 time
`

**Comment by FlexXx1212** [comment]
danke, erledigt! aber sicher dass das auch bein nem minuten timer noch passt? bin gead nich am PC

**Comment by XneddyX** [comment]
nee das geht dann nicht mehr. aber er braucht es ja nur noch für 10Stunden

**Comment by FlexXx1212** [comment]
ja okey stimmt, ich pass es dann trotzdem noch an später

XneddyX ***@***.***> schrieb am Di., 23. Apr. 2024, 19:33:

**Comment by XneddyX** [comment]
ja ich habe dafür keine "leichte und schnelle" lösung gefunden

**Comment by FlexXx1212** [comment]
habs jetzt alles ausgebessert, funktioniert jetzt immer
